script more verbose, should now work on osx and linux

diff --git a/update-sage b/update-sage
--- a/update-sage
+++ b/update-sage
@@ -24,7 +24,7 @@ if [ -d $HOME/GitBox/sage ]; then
 elif [ -d $HOME/Applications/sage-git ]; then
     SAGE_ROOT=$HOME/Applications/sage-git
 else
-    echo "update-sage: unable to set SAGE_ROOT variable"
+    echo >&2 "update-sage: unable to set SAGE_ROOT variable"
     exit 1
 fi
 cd $SAGE_ROOT
@@ -34,13 +34,15 @@ cd $SAGE_ROOT
 # http://stackoverflow.com/questions/3878624
 if [[ -z $(git status --porcelain) ]]
 then
-  echo "update-sage: tree is clean"
+    echo "update-sage: tree is clean"
 else
-  echo "update-sage: Error: tree is dirty, please commit changes or stash them before running this"
-  exit 1
+    echo >&2 "update-sage: Error: tree is dirty, please commit changes or stash them before running this"
+    exit 1
 fi
 
+echo "update-sage: checking out develop branch..."
 git checkout develop
+echo "update-sage: fetching github develop branch..."
 git fetch github develop
 
 # Check if a pull is needed in git
@@ -48,51 +50,67 @@ git fetch github develop
 LOCAL=$(git rev-parse @)
 REMOTE=$(git rev-parse @{u})
 BASE=$(git merge-base @ @{u})
-echo "update-sage: Local Branch: " $LOCAL
-echo "update-sage: Remote Branch:" $REMOTE
-echo "update-sage: Base Branch:  " $BASE
-if [ $(LOCAL) = $(REMOTE) ]; then
-    echo "update-sage: Local develop branch is up-to-date with github, we will re-build sage anyway"
-elif [ $(LOCAL) = $(BASE) ]; then
+echo "update-sage: Local develop branch: " $LOCAL
+echo "update-sage: Remote develop branch:" $REMOTE
+echo "update-sage: Base branch of both:  " $BASE
+if [ "$LOCAL" = "$REMOTE" ]; then
+    echo "update-sage: Local develop branch is up-to-date with github"
+    echo "update-sage: Since you asked, we will re-build sage anyway"
+elif [ "$LOCAL" = "$BASE" ]; then
     echo "update-sage: Local develop branch is behind github/develop, we need to pull"
+    echo "update-sage: pulling github develop branch..."
     git pull github develop
     # git merge FETCH_HEAD # or equivalently ?
-elif [ $(REMOTE) = $(BASE) ]; then
-    echo "update-sage: Error: Local develop branch has commits not in github/develop."
+elif [ "$REMOTE" = "$BASE" ]; then
+    echo >&2 "update-sage: Error: Local develop branch has commits not in github/develop."
     exit 1
 else
-    echo "update-sage: Error: Local develop branch has diverged from github/develop."
+    echo >&2 "update-sage: Error: Local develop branch has diverged from github/develop."
     exit 1
 fi
 
 # Get the number of cpus
+# another option is : sage -python src/bin/sage-num-threads.py which outputs 1 2 2
 NCPUS=`sage -c "print(sage.parallel.ncpus.ncpus())"`
-# another option is : sage -python src/bin/sage-num-threads.py
-# which outputs 1 2 2
+echo "update-sage: found $NCPUS cpus on this machine"
 
 # Make sure to use CCACHE
 # http://doc.sagemath.org/html/en/installation/source.html#environment-variables
 export SAGE_INSTALL_CCACHE=yes
 
-# Build Sage
+# make doc-clean
+echo "update-sage: running make doc-clean..."
 make doc-clean
-rm -rf logs
-export MAKE="make -j$NCPUS"
-make start
-export MAKE="make -j1"
-make doc
-export MAKE="make -j$NCPUS"
-./sage -t -p --all --long --logfile=logs/ptestlong.log #make ptestlong
+if [ $? -ne 0 ]; then
+    echo >&2 "update-sage: Error when runing make doc-clean"
+    exit 1
+fi
 
-# make doc is:
-# cd ../.. && sage-logger -p './sage --docbuild --no-pdf-links all html ' logs/dochtml.log
-# make ptestlong is:
-# ./sage -t -p --all --long --logfile=logs/ptestlong.log
+# Clean logs
+echo "update-sage: deleting logs repository..."
+rm -rf logs
+
+# Build Sage
+export MAKE="make -j$NCPUS"
+echo "update-sage: running make ptestlong..."
+make ptestlong
+if [ $? -ne 0 ]; then
+    echo >&2 "update-sage: Error when runing make ptestlong"
+    exit 1
+fi
+
+# Build Sage with 1 proc for doc
+#export MAKE="make -j$NCPUS"
+#make start
+#export MAKE="make -j1"
+#make doc
+#export MAKE="make -j$NCPUS"
+#./sage -t -p --all --long --logfile=logs/ptestlong.log
 
 # Clean branches merged into sage
 # http://stackoverflow.com/questions/6127328/how-can-i-delete-all-git-branches-which-have-been-merged 
 MERGED=$(git branch --merged develop | egrep -v "(^\*|master|develop)")
-if [ ! -z $MERGED ]; then
+if [ ! -z "$MERGED" ]; then
     echo update-sage: The following branches have been merged into sage:
     echo update-sage: $MERGED
     for BRANCH in $MERGED
