adding show-skipped option for tests

diff --git a/update-sage b/update-sage
--- a/update-sage
+++ b/update-sage
@@ -100,11 +100,14 @@ rm -rf logs
 # Build Sage
 echo "update-sage: running make -j$NCPUS ptestlong..."
 export MAKE="make -j$NCPUS"
-make ptestlong
+make
 if [ $? -ne 0 ]; then
-    echo >&2 "update-sage: Error when runing make ptestlong"
+    echo >&2 "update-sage: Error when runing make"
     exit 1
 fi
+
+# Run tests
+./sage -t -p --all --long --show-skipped --logfile=logs/ptestlong.log
 
 # Build Sage with 1 proc for doc
 #export MAKE="make -j$NCPUS"
